config/routes.rb
Rails.application.routes.draw do
  get  '/inquiry', to: 'inquiries#new'
  post '/inquiry', to: 'inquiries#create'
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/about', to: 'homes#about'
  get '/news', to: 'homes#news'
  #resources :homes
  namespace :admin do
    resources :users
  end
  root to: 'notes#index'
  resources :notes
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true 
  validates :email, presence: true
  validates :message, presence: true, length: {maximum:255}
end

app/models/note.rb
class Note < ApplicationRecord
  validates :title, presence: true, length: { maximum: 30 }
  validates :content, presence: true
  validates :maintag, presence: true, length: { maximum: 30 }

  belongs_to :user

  scope :recent, -> { order(created_at: :desc) }
  
  def self.ransackable_attributes(auth_object = nil)
    %w[title maintag]
  end

  def self.ransackable_associations(auth = nil)
    []
  end

  def self.csv_attributes
    ["title", "content", "maintag", "subtag1", "subtag2", "created_at", "updated_at"]
  end

  def self.generate_csv
    bom = "\uFEFF"
    CSV.generate(bom) do |csv|
      csv << csv_attributes
      all.each do |note|
        csv << csv_attributes.map{|attr| note.send(attr) }
      end
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: { maximum: 150 }
  belongs_to :user

  scope :recent, -> { order(created_at: :desc) }

  def self.ransackable_attributes(auth_object = nil)
    %w[name content]
  end

  def self.ransackable_associations(auth = nil)
    []
  end

  def self.csv_attributes
    ["name", "content", "created_at", "updated_at"]
  end

  def self.generate_csv
    bom = "\uFEFF"
    CSV.generate(bom) do |csv|
      csv << csv_attributes
      all.each do |task|
        csv << csv_attributes.map{|attr| task.send(attr) }
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :notes, dependent: :destroy
  has_many :tasks, dependent: :destroy
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :sex, :age, :password, :password_confirmation)
  end

  def require_admin
    redirect_to root_url unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_url unless current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :login_required
  def about
  end

  def news
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)

    if @inquiry.save
      InquiryMailer.send_mail(@inquiry).deliver_now
      redirect_to root_path, notice: "お問い合わせを受付しました。"
    else
      render :new
    end
  end

  private

  def inquiry_params
    params.permit(inquiry: [:name, :email, :message])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @q = current_user.notes.ransack(params[:q])
    @notes = @q.result(distinct: true).page(params[:page]).per(7)

    respond_to do |format|
      format.html
      format.csv { send_data @notes.generate_csv, filename: "notes-#{Time.zone.now.strftime('%Y%m%d%S')}.csv" }
    end
  end
  
  def show
    @note = current_user.notes.find(params[:id])
  end

  def new
    @note = Note.new
  end

  def create
    @note = current_user.notes.new(note_params)

    if @note.save
      redirect_to @note, notice: "ノート「#{@note.title}」を登録しました。"
    else
      render :new
    end
  end

  def edit
    @note = current_user.notes.find(params[:id])
  end

  def update
    note = current_user.notes.find(params[:id])
    note.update!(note_params)
    redirect_to notes_url, notice: "ノート「#{note.title}」を更新しました。"
  end

  def destroy
    note = current_user.notes.find(params[:id])
    note.destroy
    redirect_to notes_url, notice: "ノート「#{note.title}」を削除しました。"
  end

  private

  def note_params
    params.require(:note).permit(:title, :content, :maintag, :subtag1, :subtag2)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to admin_users_url, notice: 'ログインに成功しました。'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'ログアウトしました。'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.new(task_params)

    if @task.save
      redirect_to @task, notice: "タスク「#{@task.name}」を登録しました。"
    else
      render :new
    end
  end

  def show
    @task = current_user.tasks.find(params[:id])
  end

  def index
    @q = current_user.tasks.ransack(params[:q])
    @tasks = @q.result(distinct: true).page(params[:page]).per(7)

    respond_to do |format|
      format.html
      format.csv { send_data @tasks.generate_csv, filename: "tasks-#{Time.zone.now.strftime('%Y%m%d%S')}.csv" }
    end
  end

  def edit
    @task = current_user.tasks.find(params[:id])
  end

  def update
    task = current_user.tasks.find(params[:id])
    task.update!(task_params)
    redirect_to tasks_url, notice: "タスク「#{task.name}」を更新しました。"
  end

  def destroy
    task = current_user.tasks.find(params[:id])
    task.destroy
    redirect_to tasks_url, notice: "タスク「#{task.name}」を削除しました。"
  end

  private

  def task_params
    params.require(:task).permit(:name, :content)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li= message

= form_with model: [:admin, @user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label' do
      = f.check_box :admin, class:'form-check-input'
      | 管理者権限
  .form-group
    = f.label :age, '年齢', class: 'control-label'
    = f.select :age, [["",""], ["10代","10"], ["20代","20"], ["30代","30"], ["40代","40"], ["50代","50"], ["60代","60"], ["70代","70"]], {}, class: 'form-control'
  .form-group
    = f.label :sex, '性別', class: 'control-label'
    = f.select :sex, [["",""], ["女性","女性"], ["男性","男性"]], {}, class: 'form-control'
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード(確認)'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/admin/users/_usersform.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li= message

= form_with model: [:admin, @user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label' do
      = f.check_box :admin, class:'form-check-input'
      | 管理者権限
  .form-group
    = f.label :age, '年齢', class: 'control-label'
    = f.select :age, [["",""], ["10代","10"], ["20代","20"], ["30代","30"], ["40代","40"], ["50代","50"], ["60代","60"], ["70代","70"]], {}, class: 'form-control'
  .form-group
    = f.label :sex, '性別', class: 'control-label'
    = f.select :sex, [["",""], ["女性","女性"], ["男性","男性"]], {}, class: 'form-control'
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード(確認)'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 ユーザー編集

= render partial: 'usersform', locals: { user: @user }

app/views/admin/users/index.html.slim
h1 ユーザー一覧

.table-responsive
  table.table.table-hover
    thead.thead-dark
      tr
        th= User.human_attribute_name(:name)
        th= User.human_attribute_name(:email)
        th= User.human_attribute_name(:admin)
        th= User.human_attribute_name(:sex)
        th= User.human_attribute_name(:age)
        th= User.human_attribute_name(:created_at)
        th= User.human_attribute_name(:updated_at)
        th
    tbody
      - @users.each do |user|
        tr
          td= link_to user.name, [:admin, user]
          td= user.email
          td= user.admin? ? 'あり' : 'なし'
          td= user.sex
          td= user.age
          td= user.created_at
          td= user.updated_at
          td
            = link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mx-auto'
            = link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger mx-auto'

= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary'

app/views/admin/users/new.html.slim
h1 ユーザー登録

= render partial: 'usersform', locals: { user: @user }

app/views/admin/users/show.html.slim
h1 ユーザーの詳細

table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:id)
      td= @user.id
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= User.human_attribute_name(:admin)
      td= @user.admin? ? 'あり' : 'なし'
    tr
      th= User.human_attribute_name(:age)
      td= @user.age
    tr
      th= User.human_attribute_name(:sex)
      td= @user.sex
    tr
      th= User.human_attribute_name(:created_at)
      td= @user.created_at
    tr
      th= User.human_attribute_name(:updated_at)
      td= @user.updated_at

= link_to '編集', edit_admin_user_path, class: 'btn btn-primary mr-3'
= link_to '削除', [:admin, @user], method: :delete, data: { confirm: "ユーザー「#{@user.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/homes/about.html.slim
.about-container

.about1
  h1 Q THINKERとは？

  .panel-group#accordion
    .panel.panel-default
      .panel-heading
        h2.panel-title
          a data-toggle='collapse' data-parent='#accordion' href='#collapse1' click
      #collapse1.panel-collapse.collapse.in
        .panel-body 
          ul 
            li 思いつきのアイデアや学習中に生じた疑問などをノートに記録することで<br>
            li さらに学びを深めていくことができるアプリです。<br>

.about2
  h1 Q どんな人が対象？

  .panel-group#accordion
    .panel.panel-default
      .panel-heading
        h2.panel-title
          a data-toggle='collapse' data-parent='#accordion' href='#collapse2' click
      #collapse2.panel-collapse.collapse.in
        .panel-body 
          ul 
            li 読書をとおして思考を整理したい方<br>
            li 分野を問わずこれから学習を始ようと思っている方<br>
            li 自分の思考を整理してブログやSNSなどに発信をしたい方　etc

.about3
  h1 Q どんな機能がある？

  .panel-group#accordion
    .panel.panel-default
      .panel-heading
        h2.panel-title
          a data-toggle='collapse' data-parent='#accordion' href='#collapse3' click
      #collapse3.panel-collapse.collapse.in
        .panel-body 
          ul 
            li  アイデアなどをカテゴリに分けてノートに記録できます。<br>
            li  学習中に生じた学習タスクを登録できます。<br>
            li  登録したノート、タスクをキーワードで検索表示できます。<br>
            li  その他学習に役立つコンテンツをニュースとして随時配信しています。

.about4
  h1 Q 上手くアプリを使うには？

  .panel-group#accordion
    .panel.panel-default
      .panel-heading
        h2.panel-title
          a data-toggle='collapse' data-parent='#accordion' href='#collapse4' click
      #collapse4.panel-collapse.collapse.in
        .panel-body 
          ul 
            li  カテゴリを決めて思考や気付きなどをノートに書き留め<br>
            li  それらをストックすることで学びを深めていくことができるアプリです。

app/views/homes/contact.html.slim
.contact
  h1 <<お問い合わせ>>
  p
    |  
      アプリに関する各種お問い合わせにつきましては下記フォームよりご投稿願います。

app/views/homes/news.html.slim
  
  .news-section
    h2 NEW ARRIVAL
    .card.mb-4
      .row.no-gutters
        .col-lg-6
          img src="assets/business-4068346_640.png" class="card-img-top img-fluid" alt="ビジネス"
        .col-lg-6
          h4 class="card-title" アイデアはなぜすぐに忘れてしまう？記憶に定着させる行動3選
          p class="card-text"
            |  
              アイデアを思い浮かんでも時間が立てば不思議と忘れてしまう、といった経験は
            | 誰しもあるはず。できれば記憶に残しておきたいですよね。<br><br>そこで本記事ではアイデアを
            | 忘れないで記憶に定着させるための行動を３つにまとめて解説します。
          a href="#" 記事はこちら
    .card.mb-4
      .row.no-gutters
        .col-lg-6
          img src="assets/business-4068346_640.png" class="card-img-top img-fluid" alt="ビジネス"
        .col-lg-6
          h4 class="card-title" アイデアはなぜすぐに忘れてしまう？記憶に定着させる行動3選
          p class="card-text"
            |  
              アイデアを思い浮かんでも時間が立てば不思議と忘れてしまう、といった経験は
            | 誰しもあるはず。できれば記憶に残しておきたいですよね。<br><br>そこで本記事ではアイデアを
            | 忘れないで記憶に定着させるための行動を３つにまとめて解説します。
          a href="#" 記事はこちら

  .news-section
    h2 TOPICS INDEX
    .container
    .row
      .col-lg-4
        .card.mb-3
          img src="/assets/business-4068346_640.png" alt="ビジネス" class="card-img-top"
          .card-body
            h4 class="card-title" アイデアはなぜすぐに忘れてしまう？記憶に定着させる行動3選
            p class="card-text"
              |  
                本記事ではアイデアを
              | 忘れないで記憶に定着させるための行動を３つにまとめて解説します。<br>
            a  href="#" 記事はこちら
      .col-lg-4
        .card.mb-3
          img src="/assets/business-4068346_640.png" alt="ビジネス" class="card-img-top"
          .card-body
            h4 class="card-title" アイデアはなぜすぐに忘れてしまう？記憶に定着させる行動3選
            p class="card-text"
              |  
                本記事ではアイデアを
              | 忘れないで記憶に定着させるための行動を３つにまとめて解説します。<br>
            a  href="#" 記事はこちら
      .col-lg-4
        .card.mb-3
          img src="/assets/business-4068346_640.png" alt="ビジネス" class="card-img-top"
          .card-body
            h4 class="card-title" アイデアはなぜすぐに忘れてしまう？記憶に定着させる行動3選
            p class="card-text"
              |  
                本記事ではアイデアを
              | 忘れないで記憶に定着させるための行動を３つにまとめて解説します。<br>
            a  href="#" 記事はこちら
      .col-lg-4
        .card.mb-3
          img src="/assets/business-4068346_640.png" alt="ビジネス" class="card-img-top"
          .card-body
            h4 class="card-title" アイデアはなぜすぐに忘れてしまう？記憶に定着させる行動3選
            p class="card-text"
              |  
                本記事ではアイデアを
              | 忘れないで記憶に定着させるための行動を３つにまとめて解説します。<br>
            a  href="#" 記事はこちら
      .col-lg-4
        .card.mb-3
          img src="/assets/business-4068346_640.png" alt="ビジネス" class="card-img-top"
          .card-body
            h4 class="card-title" アイデアはなぜすぐに忘れてしまう？記憶に定着させる行動3選
            p class="card-text"
              |  
                本記事ではアイデアを
              | 忘れないで記憶に定着させるための行動を３つにまとめて解説します。<br>
            a  href="#" 記事はこちら
      .col-lg-4
        .card.mb-3
          img src="/assets/business-4068346_640.png" alt="ビジネス" class="card-img-top"
          .card-body
            h4 class="card-title" アイデアはなぜすぐに忘れてしまう？記憶に定着させる行動3選
            p class="card-text"
              |  
                本記事ではアイデアを
              | 忘れないで記憶に定着させるための行動を３つにまとめて解説します。<br>
            a  href="#" 記事はこちら

  .news-section
    h2 TOPICS MORE
    a href="#" ほかの記事も気になる方はこちら

app/views/inquiries/new.html.slim
.top-inquiry 
  | 各種お問い合わせにつきましては<br>下記フォームよりご投稿願います。

.second-inquiry
  |  申し訳ございませんが現在フォーム調整中につき<br>閉鎖しております。


= form_with url: inquiry_path, local: true do |f|
  .form-group
    = f.label :name, 'お名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, '送信先メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :message, 'お問い合わせ内容'
    = f.text_area :message, class: 'form-control'
  = f.submit '送信', class: 'btn btn-primary'

app/views/layouts/_footer.html.slim
.footer.navbar.navbar-expand-md.navbar-light.bg-light
  .copyright
  |  ©2020 THINKER <br>
  ul.navbar-nav.ml-auto
    li.nav-item= link_to 'About', about_path, class: 'nav-link'
    li.nav-item= link_to 'Contact', inquiry_path, class: 'nav-link'
    li.nav-item= link_to 'News', news_path, class: 'nav-link'

app/views/layouts/_form.html.slim
- if note.errors.present?
  ul#error_explanation
    - note.errors.full_messages.each do |message|
      li = message

= form_with model: note, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control input-lg'
  .form-group
    = f.label :maintag
    = f.text_field :maintag, class: 'form-control'
  .form-group
    = f.label :subtag1
    = f.text_field :subtag1, class: 'form-control'
  .form-group
    = f.label :subtag2
    = f.text_field :subtag2, class: 'form-control'
  = f.submit nil, class: 'btn btn-primary'

app/views/layouts/_header.html.slim
.app-title.navbar.navbar-expand-md.navbar-dark.bg-secondary
  .navbar-brand THINKER

  .justify-content-center
    ul.navbar-nav.ml-auto
      .row
        - if current_user
          li.nav-item= link_to 'Note', notes_path, class: 'nav-link'
          li.nav-item= link_to 'Task', tasks_path, class: 'nav-link'
          - if current_user.admin?
            li.nav-item= link_to 'User', admin_users_path, class: 'nav-link'
          li.nav-item= link_to 'Logout', logout_path, method: :delete, data: { confirm: "ログアウトします。よろしいですか？" }, class: 'nav-link'
        - else
          li.nav-item= link_to 'Login', login_path, class: 'nav-link'
        li.nav-item= link_to 'About', about_path, class: 'nav-link'
        li.nav-item= link_to 'News', news_path, class: 'nav-link'

app/views/layouts/_taskform.html.slim
- if task.errors.present?
  ul#error_explanation
    - task.errors.full_messages.each do |message|
      li = message

= form_with model: task, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control input-lg'
  = f.submit nil, class: 'btn btn-primary'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name='viewport' content='width=device-width, initial-scale=1.0'
    title
      | THINKER
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render partial: 'layouts/header'
    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield
    = render partial: 'layouts/footer'

app/views/notes/_form.html.slim
= form_with model: note, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control input-lg'
  .form-group
    = f.label :maintag
    = f.text_field :maintag, class: 'form-control'
  .form-group
    = f.label :subtag1
    = f.text_field :subtag1, class: 'form-control'
  .form-group
    = f.label :subtag2
    = f.text_field :subtag2, class: 'form-control'
  = f.submit nil, class: 'btn btn-primary'

app/views/notes/edit.html.slim
h1 ノートの編集

= render partial: 'layouts/form', locals: { note: @note }

app/views/notes/index.html.slim
h1 ノート一覧

= search_form_for @q, class: 'my-5' do |f|
  .form-group.row
    = f.label :title_or_maintag, 'KEYWORD', class:'col-sm-2 col-form-label'
    .col-sm-5
      = f.search_field :title_or_maintag_cont, class: 'form-control', placeholder: 'TITLE or MAINTAG'
    .form-group
      = f.submit class: 'btn btn-outline-primary mx-auto'

.mb-4
= paginate @notes
= page_entries_info @notes

.table-responsive
  table.table.table-hover 
    thead.thead-dark
      tr
        th= sort_link(@q, :title)
        th= sort_link(@q, :maintag)
        th= Note.human_attribute_name(:created_at)
        th
    tbody
      - @notes.each do |note|
        tr
          td= link_to note.title, note
          td= note.maintag
          td= note.created_at
          td
            = link_to '編集', edit_note_path(note), class: 'btn btn-outline-primary mx-auto'
            = link_to '削除', note, method: :delete, data: { confirm: "ノート[#{note.title}]を削除します。よろしいですか？" }, class: 'btn btn-outline-danger mx-auto'

= link_to 'CSV出力', notes_path(format: :csv), class: 'btn btn-outline-primary'

= link_to 'ノート作成', new_note_path, class: 'btn btn-primary'
= link_to 'タスク作成', new_task_path, class: 'btn btn-primary'

app/views/notes/new.html.slim
h1 ノート新規作成 

= render partial: 'layouts/form', locals: { note: @note }

app/views/notes/show.html.slim
h1 ノートの詳細

table.table.table-hover
  tbody
    tr
      th= Note.human_attribute_name(:title)
      td= @note.title
    tr
      th= Note.human_attribute_name(:content)
      td= simple_format(h(@note.content), {}, sanitize: false, wrapper_tag: "div")
    tr
      th= Note.human_attribute_name(:maintag)
      td= @note.maintag
    tr
      th= Note.human_attribute_name(:subtag1)
      td= @note.subtag1
    tr
      th= Note.human_attribute_name(:subtag2)
      td= @note.subtag2
    tr
      th= Note.human_attribute_name(:created_at)
      td= @note.created_at
    tr
      th= Note.human_attribute_name(:updated_at)
      td= @note.updated_at

= link_to '編集', edit_note_path, class: 'btn btn-primary mx-auto'
= link_to '削除', @note, method: :delete, data: { confirm: "ノート[#{@note.title}]を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/tasks/edit.html.slim
h1 タスクの編集

= render partial: 'layouts/taskform', locals: { task: @task }

app/views/tasks/index.html.slim
h1 タスク一覧

= search_form_for @q, class: 'my-5' do |f|
  .form-group.row
    = f.label :name_or_content, 'KEYWORD', class:'col-sm-2 col-form-label'
    .col-sm-5
      = f.search_field :name_or_content_cont, class: 'form-control', placeholder: 'NAME or CONTENT'
    .form-group
      = f.submit class: 'btn btn-outline-primary'

.mb-4
= paginate @tasks
= page_entries_info @tasks

.col-sm-3
table.table.table-hover 
  thead.thead-dark
    tr
      th= Task.human_attribute_name(:name)
      th= Task.human_attribute_name(:content)
      th= Task.human_attribute_name(:created_at)
      th
  tbody
    - @tasks.each do |task|
      tr
        td= link_to task.name, task
        td= task.content
        td= task.created_at
        td
          = link_to '編集', edit_task_path(task), class: 'btn btn-outline-primary mx-auto'
          = link_to '削除', task, method: :delete, data: { confirm: "タスク[「#{task.name}」を削除します。よろしいですか？" }, class: 'btn btn-outline-danger'

= link_to 'CSV出力', tasks_path(format: :csv), class: 'btn btn-outline-primary'

= link_to 'ノート作成', new_note_path, class: 'btn btn-primary'
= link_to 'タスク作成', new_task_path, class: 'btn btn-primary'

app/views/tasks/new.html.slim
h1 タスク新規作成

= render partial: 'layouts/taskform', locals: { task: @task }

app/views/tasks/show.html.slim
h1 タスクの詳細

table.table.table-hover
  tbody
    tr
      th= Task.human_attribute_name(:name)
      td= @task.name
    tr
      th= Task.human_attribute_name(:content)
      td= simple_format(h(@task.content), {}, sanitize: false, wrapper_tag: "div")
    tr
      th= Task.human_attribute_name(:created_at)
      td= @task.created_at
    tr
      th= Task.human_attribute_name(:updated_at)
      td= @task.updated_at

= link_to '編集', edit_task_path, class: 'btn btn-primary mx-auto'
= link_to '削除', @task, method: :delete, data: { confirm: "ノート「#{@task.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'